####################################################
#                                                  #
#                   LOVELACE                       #
#                                                  #
####################################################

custom_header:
  compact_mode: true
  button_text:
    options: '{{ hours12LZ }}:{{ minutesLZ }}'
  hide_help: true
  hide_config: true
  shadow: on
  chevrons: false

title: Home
background: var(--background-image)
views:
  - !include lovelace/rooms.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/data.yaml
  - !include lovelace/switches.yaml
#  - !include lovelace/devicestatus.yaml (Now a seperate dashboard)
#  - !include lovelace/ha.yaml (Now a seperate dashboard)
#  - !include lovelace/network.yaml (Now a seperate dashboard)
  - !include lovelace/automations.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/googlehomehub.yaml

####################################################
#                                                  #
#          END OF CONFIGURATION FILE               #
#                                                  #
####################################################
