#########################################################
#                                                       #
#                 LEAVING HOME                          #
#                                                       #
#########################################################

- alias: Leaving Home
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.adam
    - platform: state
      entity_id: gperson.amy
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('person.adam') != 'home' }}"
      - condition: template
        value_template: "{{ states('person.amy') != 'home' }}"
      - condition: template  
        value_template: "{{ states('input_boolean.guest_mode') != 'on' }}"
  action:
    - service: switch.turn_off
      entity_id:
        - switch.kuled1
        - switch.kuled2
        - switch.basic1
    - service: light.turn_off
      entity_id:
        - light.tradfri_bulb_e26_ws_opal_980lm_3
        - light.tradfri_bulb_e26_ws_opal_980lm_2_2
        - light.zooz_zen27_s2_dimmer_wall_switch_level
        - light.zooz_zen27_s2_dimmer_wall_switch_level_2
        - light.zooz_zen27_s2_dimmer_wall_switch_level_3

########################################################
#                                                      #
#             END OF CONFIGURATION FILE                #
#                                                      #
########################################################
